@startuml Tugas 6
start
:Display (Menu Jualan);
        if (pilih == 1) then (case 1)
                :input (qty);
                :get (total);
        elseif (pilih == 2) then (case2)
                :input (qty);
                :get (total);
        elseif (pilih == 3) then (case3)
                :input (qty);
                :get (total);
        elseif (pilih == 4) then (case4)
                :input (qty);
                :get (total);
        else
                :Display "Tidak ada pilihan!";
        endif
stop
@enduml